name: SHRPBuilder

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: "SHRP Branch"
        required: true
        default: "shrp-12.1"
        type: choice
        options:
          - shrp-12.1
          - shrp-9.0

      DEVICE_TREE:
        description: "Device Tree Repo"
        required: true
        default: "https://github.com/christiandroid20/android_device_samsung_a35x"

      DEVICE_TREE_BRANCH:
        description: "Device Tree Branch"
        required: true
        default: "android-12.1"

      BUILD_TARGET:
        description: "Build Target"
        required: true
        default: "recovery"
        type: choice
        options:
          - recovery
          - boot
          - vendor_boot

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      DEVICE_MAKEFILE: omni_a35x
      DEVICE_NAME: a35x
      ALLOW_MISSING_DEPENDENCIES: true

      FOX_TARGET_DEVICES: a35x
      FOX_BUILD_DEVICE: a35x
      FOX_BUILD_TYPE: Release

      SHRP_BUILD_TYPE: Release

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y git curl bc bison build-essential zip unzip flex gperf python3 ccache libncurses5-dev libssl-dev

    - name: Install repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod +x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Setup ccache
      run: |
        ccache -M 10G
        ccache -z

    - name: Init repo
      run: |
        mkdir android-recovery && cd android-recovery
        repo init -u https://github.com/SHRP-Reborn/manifest.git -b ${{ inputs.MANIFEST_BRANCH }} --depth=1

    - name: Sync repo
      run: |
        cd android-recovery
        repo sync -c -j$(nproc --all) --force-sync --no-tags --optimized-fetch

    - name: Fix vendor shrp
      run: |
        cd android-recovery
        if [ ! -d "vendor/shrp" ]; then
          git clone https://github.com/SHRP-Reborn/android_vendor_shrp vendor/shrp
        fi

    - name: Clone device tree
      run: |
        cd android-recovery
        git clone --depth=1 ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} device/samsung/a35x

    - name: Build SHRP
      run: |
        cd android-recovery

        export CCACHE_DIR=$HOME/.ccache
        export ALLOW_MISSING_DEPENDENCIES=true
        export SHRP_BUILD_TYPE=Release

        source build/envsetup.sh

        echo "👉 Lunching: $DEVICE_MAKEFILE-eng"
        lunch $DEVICE_MAKEFILE-eng || exit 1
        
        mka ${{ inputs.BUILD_TARGET }}image -j$(nproc --all)

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.run_id }}
        name: SHRP A35x ${{ inputs.BUILD_TARGET }}
        files: |
          android-recovery/out/target/product/${{ env.DEVICE_NAME }}/*.img
          android-recovery/out/target/product/${{ env.DEVICE_NAME }}/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
